lftp-path:
private-keyfile:
public-keyfile:
username:
password:
working-dir:
speed-limit: 0
connection-limit: 25
transfer-limit: 3
max-retries: 5
newer-than:
zip-sources: false
speed-schedule:
source-target-map:
post-processors:
notifications:
  prowl:
    enable: false
    events: [transferStarted, transferComplete, transferFailed]
    api-key:
  pushover:
    enable: false
    events: [transferStarted, transferComplete, transferFailed]
    api-token:
    user-key:
  pushsafer:
    enable: false
    events: [transferStarted, transferComplete, transferFailed]
    private-key: